version: '3.7'
services:
  db:
    image: postgres:latest
    volumes:
      - ./.docker/postgres/:/var/lib/postgresql/data
      - ./docker-create-test-db.sh:/docker-entrypoint-initdb.d/docker-create-test-db.sh
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: learn-phoenix-in-action
      POSTGRES_DB_TEST: learn-phoenix-in-action-test
    ports:
      - '5433:5432' # 5433 port

